### ISSUE TITLE
dash.exceptions.DuplicateIdError

### ISSUE THREAD

**Issue by Saliva520319** [plotly/dash-web-trader#2]
Work on 10.12.6 sierra.
python version 2.7.14
follow directions but when I run python app.py , I meet the error:

dash.exceptions.DuplicateIdError
Traceback (most recent call last):
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/dash/dash.py", line 893, in _setup_server
    self._validate_layout()
  File "/Users/chufengze/dash-web-trader-venv/lib/python2.7/site-packages/dash/dash.py", line 886, in _validate_layout
    ' in the initial layout: `{}`'.format(component_id))
DuplicateIdError: Duplicate component id found in the initial layout: `modal_pair`

hope you can understand my problem.

**Comment by Saliva520319** [comment]
use python 3.6.6. by pyenv also meet this problem
Traceback (most recent call last):
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 1808, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/flask/app.py", line 1855, in try_trigger_before_first_request_functions
    func()
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dash/dash.py", line 893, in _setup_server
    self._validate_layout()
  File "/Users/chufengze/.pyenv/versions/3.6.6/lib/python3.6/site-packages/dash/dash.py", line 886, in _validate_layout
    ' in the initial layout: `{}`'.format(component_id))
dash.exceptions.DuplicateIdError: Duplicate component id found in the initial layout: `modal_pair`

**Comment by thoughtsociety** [comment]
I am seeing similar errors when running locally on Sierra 10.12.6

**Comment by massimocavallin** [comment]
Same problem for me. Has anyone found the solution?

**Comment by amadoukane96** [comment]
@Saliva520319 @thoughtsociety  @massimocavallin  Sorry for this, there is this , can you retry with the latest code ?

**Comment by Saliva520319** [comment]
@amadoukane96 lates code seems work well. Thankss.

**Comment by jared-lieberman** [comment]
Can you explain this error? I am working on an application that worked but raised this error when I updated to 0.26.6. Thanks a lot!
